// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: person.proto

package com.demo.grpc;

public interface RequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.demo.grpc.Request)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int32 id = 2;</code>
   */
  int getId();

  /**
   * <code>bytes content = 3;</code>
   */
  com.google.protobuf.ByteString getContent();
}
