// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: person.proto

package com.demo.grpc;

public interface ResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.demo.grpc.Response)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
